export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout(...properties) {
    // @ts-ignore
    const { children } = properties[0];

    console.log(properties);

    return (
        <html lang="en">
            <body>
                <h1>YEEET</h1>
                {children}
            </body>
        </html>
    );
}
