import '@/styles/tailwind.css';
import 'focus-visible';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout(properties) {
    const { children } = properties;

    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
